-- ============================================================
-- FinSight: Teardown
-- WARNING: This permanently deletes all FinSight objects
-- ============================================================

USE DATABASE FINSIGHT_DB;
USE SCHEMA FINSIGHT_SCHEMA;

DROP CORTEX SEARCH SERVICE IF EXISTS FINSIGHT_SEARCH_SERVICE;
DROP TABLE IF EXISTS DOCUMENT_CHUNKS;
DROP STAGE IF EXISTS DOCS_STAGE;
DROP SCHEMA IF EXISTS FINSIGHT_SCHEMA;
DROP DATABASE IF EXISTS FINSIGHT_DB;
DROP WAREHOUSE IF EXISTS FINSIGHT_WH;
